# MailManager 기본 설정 파일

# 기본 언어 설정 (ko 또는 en 등)
default-language: en

# 우편 알림 반복 간격 (초 단위)
mail-reminder-interval: 300

# 데이터 저장 주기 (초 단위)
auto-save-interval: 300

# 발송 제한 (일괄 발송 최대 수신자 수)
send-all-limit: 1000

# GUI 페이지당 표시할 항목 수
gui:
  mails-per-page: 36
  players-per-page: 45

# 데이터베이스 설정 (현재는 SQLite만 지원)
database:
  type: sqlite
  file-name: mail_data.db
