default-language: en_us

database:
  # USED DATABASE TYPE (SQLITE | MYSQL | YAML)
  type: SQLITE

  # --- SQLITE ---
  sqlite:
    file: plugins/MailManager/mail.db

  # --- MYSQL ---
  mysql:
    host: localhost
    port: 3306
    name: maildb
    user: root
    pass: password
    pool:
      maximumPoolSize: 10
      minimumIdle: 2
      connectionTimeoutMs: 10000
      idleTimeoutMs: 60000
      maxLifetimeMs: 1800000

  # --- YAML ---
  yaml:
    folder: plugins/MailManager/data/

flush:
  intervalTicks: 100   # DEFAULT: 100 TICKS (=5 SECONDS)

items:
  mail:
    gui:
      select-button:
        material: YELLOW_DYE
        custom-model-data: 0
        damage: 0
        hide-flags: false
      claim-selected-button:
        material: ENDER_CHEST
        custom-model-data: 0
        damage: 0
        hide-flags: false
      delete-selected-button:
        material: RED_CONCRETE
        custom-model-data: 0
        damage: 0
        hide-flags: false
      send-button:
        material: WRITABLE_BOOK
        custom-model-data: 0
        damage: 0
        hide-flags: false
      setting-button:
        material: COMPARATOR
        custom-model-data: 0
        damage: 0
        hide-flags: false
      claim-button:
        material: CHEST
        custom-model-data: 0
        damage: 0
        hide-flags: false
      delete-button:
        material: RED_WOOL
        custom-model-data: 0
        damage: 0
        hide-flags: false
  page:
    next-button:
      material: ARROW
      custom-model-data: 0
      damage: 0
      hide-flags: false
    previous-button:
      material: ARROW
      custom-model-data: 0
      damage: 0
      hide-flags: false
  back-button:
    material: BARRIER
    custom-model-data: 0
    damage: 0
    hide-flags: false
  setting:
    notify-on:
      material: LIME_DYE
      custom-model-data: 0
      damage: 0
      hide-flags: false
    notify-off:
      material: GRAY_DYE
      custom-model-data: 0
      damage: 0
      hide-flags: false
    blacklist:
      material: BARRIER
      custom-model-data: 0
      damage: 0
      hide-flags: false
    language:
      material: BOOK
      custom-model-data: 0
      damage: 0
      hide-flags: false
  language:
    gui-item:
      material: PAPER
      custom-model-data: 0
      damage: 0
      hide-flags: false
  send:
    gui:
      time:
        material: CLOCK
        custom-model-data: 0
        damage: 0
        hide-flags: false
      target:
        material: PLAYER_HEAD
        custom-model-data: 0
        damage: 0
        hide-flags: false
      confirm:
        material: GREEN_WOOL
        custom-model-data: 0
        damage: 0
        hide-flags: false
  sendall:
    gui:
      time:
        material: CLOCK
        custom-model-data: 0
        damage: 0
        hide-flags: false
      exclude:
        material: BARRIER
        custom-model-data: 0
        damage: 0
        hide-flags: false
      attach:
        material: CHEST
        custom-model-data: 0
        damage: 0
        hide-flags: false
      confirm:
        material: GREEN_WOOL
        custom-model-data: 0
        damage: 0
        hide-flags: false
  time:
    gui:
      unit:
        material: CLOCK
        custom-model-data: 0
        damage: 0
        hide-flags: false
      permanent:
        material: BARRIER
        custom-model-data: 0
        damage: 0
        hide-flags: false
      chat-input:
        material: WRITABLE_BOOK
        custom-model-data: 0
        damage: 0
        hide-flags: false
      confirm:
        material: LIME_CONCRETE
        custom-model-data: 0
        damage: 0
        hide-flags: false
  blacklist:
    exclude-search:
      material: COMPASS
      custom-model-data: 0
      damage: 0
      hide-flags: false
  delete:
    gui:
      confirm-button:
        material: RED_WOOL
        custom-model-data: 0
        damage: 0
        hide-flags: false
      cancel-button:
        material: GREEN_WOOL
        custom-model-data: 0
        damage: 0
        hide-flags: false

sounds:
  gui:
    click:
      name: UI_BUTTON_CLICK
      volume: 1.0
      pitch: 1.0
    click-fail:
      name: BLOCK_NOTE_BLOCK_BASS
      volume: 0.8
      pitch: 0.8
    page-turn:
      name: ITEM_BOOK_PAGE_TURN
      volume: 1.0
      pitch: 1.2
  mail:
    claim-success:
      name: ENTITY_ITEM_PICKUP
      volume: 1.0
      pitch: 1.0
    claim-fail:
      name: ENTITY_VILLAGER_NO
      volume: 1.0
      pitch: 1.0
    delete-success:
      name: BLOCK_ANVIL_LAND
      volume: 1.0
      pitch: 0.7
    send-success:
      name: ENTITY_PLAYER_LEVELUP
      volume: 1.0
      pitch: 1.0
    receive-notification:
      name: UI_TOAST_IN
      volume: 1.0
      pitch: 1.0
    reminder:
      name: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 1.0
      pitch: 1.0
  action:
    setting-change:
      name: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 1.0
      pitch: 1.0
    selection-complete:
      name: BLOCK_NOTE_BLOCK_PLING
      volume: 1.0
      pitch: 1.0
