items:
  mail:
    gui:
      send-button:
        material: WRITABLE_BOOK
        custom-model-data: 0
        damage: 0
        hide-flags:
          - HIDE_ENCHANTS
          - HIDE_ATTRIBUTES
          - HIDE_UNBREAKABLE
          - HIDE_DESTROYS
          - HIDE_PLACED_ON
          - HIDE_POTION_EFFECTS
      setting-button:
        material: COMPARATOR
        custom-model-data: 0
        damage: 0
        hide-flags: false
        unbreakable: false
  page:
    next-button:
      material: ARROW
      custom-model-data: 0
      damage: 0
      hide-flags: false
    previous-button:
      material: ARROW
      custom-model-data: 0
      damage: 0
      hide-flags: false
  back-button:
    material: BARRIER
    custom-model-data: 0
    damage: 0
    hide-flags: false
  setting:
    notify-on:
      material: LIME_DYE
      custom-model-data: 0
      damage: 0
      hide-flags: false
    notify-off:
      material: GRAY_DYE
      custom-model-data: 0
      damage: 0
      hide-flags: false
    blacklist:
      material: BARRIER
      custom-model-data: 0
      damage: 0
      hide-flags: false
    language:
      material: BOOK
      custom-model-data: 0
      damage: 0
      hide-flags: false
  language:
    gui-item:
      material: PAPER
      custom-model-data: 0
      damage: 0
      hide-flags: false
  send:
    gui:
      time:
        material: CLOCK
        custom-model-data: 0
        damage: 0
        hide-flags: false
      target:
        material: PLAYER_HEAD
        custom-model-data: 0
        damage: 0
        hide-flags: false
      confirm:
        material: GREEN_WOOL
        custom-model-data: 0
        damage: 0
        hide-flags: false
  sendall:
    gui:
      time:
        material: CLOCK
        custom-model-data: 0
        damage: 0
        hide-flags: false
      exclude:
        material: BARRIER
        custom-model-data: 0
        damage: 0
        hide-flags: false
      confirm:
        material: GREEN_WOOL
        custom-model-data: 0
        damage: 0
        hide-flags: false
  time:
    gui:
      unit:
        material: CLOCK
        custom-model-data: 0
        damage: 0
        hide-flags: false
      permanent:
        material: BARRIER
        custom-model-data: 0
        damage: 0
        hide-flags: false
      chat-input:
        material: WRITABLE_BOOK
        custom-model-data: 0
        damage: 0
        hide-flags: false
      confirm:
        material: LIME_CONCRETE
        custom-model-data: 0
        damage: 0
        hide-flags: false
  blacklist:
    exclude-search:
      material: COMPASS
      custom-model-data: 0
      damage: 0
      hide-flags: false
  delete:
    gui:
      confirm-button:
        material: RED_WOOL
        custom-model-data: 0
        damage: 0
        hide-flags: false
      cancel-button:
        material: GREEN_WOOL
        custom-model-data: 0
        damage: 0
        hide-flags: false

sounds:
  gui:
    click: UI_BUTTON_CLICK
    click-fail: BLOCK_NOTE_BLOCK_BASS
    page-turn: ITEM_BOOK_PAGE_TURN
  mail:
    claim-success: ENTITY_ITEM_PICKUP
    claim-fail: ENTITY_VILLAGER_NO
    delete-success: BLOCK_ANVIL_LAND
    send-success: ENTITY_PLAYER_LEVELUP
    receive-notification: UI_TOAST_IN
    reminder: ENTITY_EXPERIENCE_ORB_PICKUP
  action:
    setting-change: ENTITY_EXPERIENCE_ORB_PICKUP
    selection-complete: BLOCK_NOTE_BLOCK_PLING
