gui-items:
  back:
    material: BARRIER
    name: "&c뒤로가기"
    lore:
      - "&7이전 메뉴로 돌아갑니다"

  previous-page:
    material: ARROW
    name: "&a◀ 이전 페이지"
    lore:
      - "&7이전 페이지로 이동"

  next-page:
    material: ARROW
    name: "&a▶ 다음 페이지"
    lore:
      - "&7다음 페이지로 이동"

  mail-send:
    material: PAPER
    name: "&a메일 보내기"
    lore:
      - "&7메일을 전송합니다"

  setting:
    material: COMPARATOR
    name: "&b설정"
    lore:
      - "&7메일 설정 열기"

  blacklist:
    material: NETHER_BRICK
    name: "&c차단 목록"
    lore:
      - "&7메일 차단 대상 관리"

  permanent:
    material: CLOCK
    name: "&6영구 설정"
    lore:
      - "&7만료 없이 메일 보내기"

  select-complete:
    material: EMERALD_BLOCK
    name: "&a선택 완료"
    lore:
      - "&7선택을 완료하고 다음 단계로 이동"
