gui-items:
  back:
    material: BARRIER
    name: "&cBack"
    lore:
      - "&7Return to the previous menu"

  previous-page:
    material: ARROW
    name: "&a◀ Previous"
    lore:
      - "&7Go to the previous page"

  next-page:
    material: ARROW
    name: "&a▶ Next"
    lore:
      - "&7Go to the next page"

  mail-send:
    material: PAPER
    name: "&aSend Mail"
    lore:
      - "&7Click to send mail"

  setting:
    material: COMPARATOR
    name: "&bSettings"
    lore:
      - "&7Open mail settings"

  blacklist:
    material: NETHER_BRICK
    name: "&cBlacklist"
    lore:
      - "&7Manage your mail blacklist"

  permanent:
    material: CLOCK
    name: "&6Permanent"
    lore:
      - "&7Send mail without expiration"

  select-complete:
    material: EMERALD_BLOCK
    name: "&aSelect Complete"
    lore:
      - "&7Confirm selection and continue"
