# MailManager Config File

# Set default language (ko or en, etc.)
default-language: en

# Data auto-save cycle (in seconds)
auto-save-interval: 300

# --- GUI Item Setting ---
# Use the Bukkit Item Name. (예: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html)
items:
  mail_gui:
    send_button:
      material: WRITABLE_BOOK
      damage: 0
      custom-model-data: 0
      hide-flags: false
    setting_button: COMPARATOR
  page:
    next_button: ARROW
    previous_button: ARROW
  back_button: BARRIER
  setting_gui:
    notify_on: LIME_DYE
    notify_off: GRAY_DYE
    blacklist_button: BARRIER
    language_button: BOOK
  language_gui:
    language_item: PAPER
  send_gui:
    time_button: CLOCK
    target_button: PLAYER_HEAD
    confirm_button: GREEN_WOOL
  send_all_gui:
    exclude_button: BARRIER
    confirm_button: GREEN_WOOL
  time_gui:
    time_unit_item: CLOCK
    permanent_button: BARRIER
    chat_input_button: WRITABLE_BOOK
    confirm_button: LIME_CONCRETE
  blacklist_exclude_gui:
    search_button: COMPASS
  delete_gui:
    confirm_button: RED_WOOL
    cancel_button: GREEN_WOOL

# --- Sound Effect Settings ---
## Use the Bukkit Sound name. (Example: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html)
sounds:
  gui:
    click: UI_BUTTON_CLICK
    click_fail: BLOCK_NOTE_BLOCK_BASS
    page_turn: ITEM_BOOK_PAGE_TURN
  mail:
    claim_success: ENTITY_ITEM_PICKUP
    claim_fail: ENTITY_VILLAGER_NO
    delete_success: BLOCK_ANVIL_LAND
    send_success: ENTITY_PLAYER_LEVELUP
    receive_notification: UI_TOAST_IN
  action:
    setting_change: ENTITY_EXPERIENCE_ORB_PICKUP
    selection_complete: BLOCK_NOTE_BLOCK_PLING