name: MailManager
version: 21.0
main: com.gmail.bobason01.MailManager
api-version: 1.16
author: crston
commands:
  mail:
    description: Opens the mail GUI or manages mail commands.
    usage: /mail [subcommand]
permissions:
  mail.use:
    description: Allows opening the mailbox.
    default: true
  mail.send:
    description: Allows sending mail to other players.
    default: true
  mail.sendall:
    description: Allows sending global mail to all players.
    default: op
  mail.admin:
    description: Admin permissions (reload, setlang, reset).
    default: op
  mail.inv.manage:
    description: Allows creating/editing virtual inventories.
    default: op