name: MailManager
version: 8.0
main: com.gmail.bobason01.MailManager
api-version: 1.16
author: bobason01
commands:
  mail:
    description: Mail System Command
    usage: /mail [send | sendall | reload | setlang]
permissions:
  mail.use:
    description: Allows players to use the mail system
    default: true
  mail.admin:
    description: Allows access to administrative mail features
    default: op